# Generated by Django 4.1.7 on 2023-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200, unique=True)),
                ('card_image', models.CharField(max_length=200)),
                ('card_type', models.CharField(max_length=200)),
                ('cmc', models.IntegerField()),
                ('mana_cost', models.CharField(max_length=200)),
                ('power', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('oracle_text', models.CharField(max_length=200)),
                ('legalities', models.CharField(max_length=200)),
            ],
        ),
    ]
