# Generated by Django 4.1.7 on 2023-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='oracle_text',
            field=models.CharField(max_length=500),
        ),
    ]
